[toolchain]
channel = "stable"  # toolchain baseline
components = ["rustfmt", "clippy", "rust-src", "llvm-tools"]
edition = "2024"
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "wasm32-wasi",
    "aarch64-apple-darwin",
    "riscv32imc-unknown-none-elf"
]
