[package]
name = "zulon-ext-serde"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

# TODO: Add dependencies when needed
[dependencies]

[dev-dependencies]
