[package]
name = "zulon-diagnostic"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
termcolor = "1.4"
textwrap = "0.16"
unicode-width = "0.1"
thiserror = "2.0"
